<a href="https://colab.research.google.com/github/stanleytenz/Non-GradedChallenge/blob/main/P0LC2_Stanley_Armando.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

=================================================================================================================

**Live Code 2**

Nama  : Stanley Armando Austen

Batch : FTDS - 027

Program ini dibuat untuk melakukan analisa terhadap data perjalanan dari penyedia jasa transportasi di suatu kota. Program ini terdiri dari Explorasi DAta menggunakan SQL pada bagian 1, dan analisa data lanjutan menggunakan pandas pada bagian 2.

=================================================================================================================

In [1]:
'''
Ini adalah code untuk menyambungkan notebook dengan server bigquery
'''
from google.colab import auth
from google.cloud import bigquery
auth.authenticate_user()
print('Authenticated')

project_id_akun = "dummy-456310" # Gunakan GCP Project-ID Anda
client = bigquery.Client(project=project_id_akun)

Authenticated

In [2]:
'''
Ini adalah code untuk pengambilan data dari bigquery
'''
df_1 = client.query(
    '''
SELECT *
FROM `ftds-hacktiv8-project.phase0_ftds_027_hck.taxi_fare`

'''
).to_dataframe()

df_1 # menampilkan dataframe

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_km,fare,tips,payment_type,company,pickup_location,dropoff_location
0,AI-10273,A-318,2021-02-09 18:30:00+00:00,2021-02-09 18:30:00+00:00,0.482802,4.50,0.0,Cash,Atomic Inc.,POINT (-87.6251921424 41.8788655841),POINT (-87.6333080367 41.899602111)
1,AI-10159,A-318,2021-01-08 15:45:00+00:00,2021-01-08 16:00:00+00:00,1.770274,8.25,0.0,Cash,Atomic Inc.,POINT (-87.6635175498 41.874005383),POINT (-87.6251921424 41.8788655841)
2,AI-10889,A-318,2021-04-06 10:45:00+00:00,2021-04-06 10:45:00+00:00,3.540548,9.25,0.0,Cash,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6203346241 41.8571838585)
3,AI-10670,A-324,2021-03-18 15:30:00+00:00,2021-03-18 15:45:00+00:00,1.448406,5.75,0.0,Cash,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6333080367 41.899602111)
4,AI-10929,A-324,2021-04-08 19:15:00+00:00,2021-04-08 19:45:00+00:00,21.082354,34.75,0.0,Credit Card,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6488950721 41.7174930361)
...,...,...,...,...,...,...,...,...,...,...,...
9281,DP-784,D-51,2021-08-22 20:45:00+00:00,2021-08-22 21:15:00+00:00,28.968120,44.25,30.0,Credit Card,Deluc Porter,POINT (-87.9030396611 41.9790708201),POINT (-87.6188683546 41.8909220259)
9282,DP-927,P-116,2021-09-21 21:00:00+00:00,2021-09-21 21:30:00+00:00,29.450922,45.00,30.0,Credit Card,Deluc Porter,POINT (-87.9030396611 41.9790708201),POINT (-87.6209929134 41.8849871918)
9283,DP-174,D-113,2021-04-02 14:45:00+00:00,2021-04-02 16:15:00+00:00,99.296278,146.00,32.2,Credit Card,Deluc Porter,POINT (-87.913624596 41.9802643146),POINT (-87.913624596 41.9802643146)
9284,AI-11519,AI-555,2021-05-18 16:45:00+00:00,2021-05-18 17:45:00+00:00,20.921420,3.25,33.0,Credit Card,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.7696154528 41.7925923603)
9285,FI-3194,I-407,2022-06-19 20:45:00+00:00,2022-06-19 21:15:00+00:00,10.782578,21.00,100.0,Credit Card,Federway Int.,POINT (-87.6559981815 41.9442266014),POINT (-87.6763559892 41.9012069941)

In [3]:
'''
Ini adalah code untuk menampilkan unique value dari kolom company

penjelasan:
kita menampilkan unique value dengan menggunakan distinct dari kolom company

analisa:
Dari sini kita bisa melihat bahwa ada 5 company yang berbeda dalam penyediaan layanan taksi yang terdapat pada dataset tersebut.
company tersebut yaitu: Atomic Inc, Deluc Porter,Federway Int, Synctaxi Inc, dan Rocket Cab Auto.

'''
df_1 = client.query(
    '''
SELECT distinct company
FROM `ftds-hacktiv8-project.phase0_ftds_027_hck.taxi_fare`

'''
).to_dataframe()

df_1 # menampilkan dataframe

'\nDari sini kita bisa melihat bahwa ada 5 company yang berbeda dalam penyediaan layanan taksi yang terdapat pada dataset tersebut.\ncompany tersebut yaitu: Atomic Inc, Deluc Porter,Federway Int, Synctaxi Inc, dan Rocket Cab Auto.\n'

In [4]:
'''
Ini adalah code untuk memperlihatkan data minimal dan data maximal dari kolom trip_start_timestamp

penjelasan:
kita menggunakan fungsi min dari kolom trip_start_timestamp lalu diberi nama sebagai min_pengambilan data
lalu menggunakan fungsi max dari kolom trip_start_timestamp lalu diberi nama sebagai max_pengambilan_data

analisa:
DAri sini kita bisa melihat bahwa untuk minimal waktu pengambilan data adalah pada tanggal 2 february 2021 pukul 11 pagi (diwakilkan oleh kolom min_pengambilan_data)
dan waktu maksimum dari pengambilan data yaitu pada tanggal 31 december 2022 pukul 14.15 (diwakilkan oleh kolom max_pengambilan_data)

Saya menggunakan trip_start_timestamp dan bukan trip_end_timestamp karena data dibuat pada saat pelanggan memesan transaksi bukan pada saat mereka selesai transaksi
'''
df_1 = client.query(
    '''
SELECT min(trip_start_timestamp) as min_pengambilan_data, max(trip_start_timestamp) as max_pengambilan_data
FROM `ftds-hacktiv8-project.phase0_ftds_027_hck.taxi_fare`

'''
).to_dataframe()

df_1

'\nDAri sini kita bisa melihat bahwa untuk minimal waktu pengambilan data adalah pada tanggal 2 february 2021 pukul 11 pagi (diwakilkan oleh kolom min_pengambilan_data)\ndan waktu maksimum dari pengambilan data yaitu pada tanggal 31 december 2022 pukul 14.15 (diwakilkan oleh kolom max_pengambilan_data)\n\nSaya menggunakan trip_start_timestamp dan bukan trip_end_timestamp karena data dibuat pada saat pelanggan memesan transaksi bukan pada saat mereka selesai transaksi\n'

In [5]:
'''
Ini adalah code untuk memperlihatkan dari seluruh total perjalanan (km) untuk setiap company pada tahun 2022

penjelasan:
kita menghitung total trip dengan menjumlahkan kolom trip_km berdasarkan company masing masing lalu dibebri nama total perjalanan

analisa:
Disini kita melihat bahwa perjalanan yang ditempuh terbanyak yaitu company Deluc Porter	dengan 18515.21 km
Dan yang terkecil adalah company Rocket Cab Auto sebanyak 1031.09 km
Disini hanya tercantum 4 company karena 1 company yang lain yaitu Atomic Inc. tidak melakukan transaksi pada tahun 2022
'''
df_1 = client.query(
    '''
SELECT company, sum(trip_km) as total_perjalanan
FROM `ftds-hacktiv8-project.phase0_ftds_027_hck.taxi_fare`
where trip_start_timestamp >= '2022-01-01' and trip_start_timestamp <= '2022-12-31'
group by company


'''
).to_dataframe()

df_1

'\nDisini kita melihat bahwa perjalanan yang ditempuh terbanyak yaitu company Deluc Porter\tdengan 18515.21 km\nDan yang terkecil adalah company Rocket Cab Auto sebanyak 1031.09 km\n\nDisini hanya tercantum 4 company karena 1 company yang lain yaitu Atomic Inc. tidak melakukan transaksi pada tahun 2022\n'

In [6]:
'''
Ini code untuk mencari average price per km berdasarkan company

penjelasan:
disini kita menggunakan subquery.

langkah pertama yaitu kita mencari nilai average dari jarak berdasarkan company nya lalu disimpan sebagai avg_trip_km
lalu mencari nilai average dari harga berdasarkan company nya juga dan disimpan sebagai avg_fare_company
setelah menjadi 1 query yang memiliki nilai avg_trip_km dan avg_fare_company
kita mengambil mencari nilai avg_price_per_km dengan menggunakan rumus avg_fare_company dibagi dengan avg_trip_km

analisa:
Dari sini kita bisa melihat bahwa company Atomic Inc.	memiliki harga paling mahal yaitu dengan tarif 2.40 per km nya
lalu untuk yang paling murah adalah company Rocket Cab Auto	dengan taruk 1.67 per km nya
'''
df_1 = client.query(
    '''

select x.company, x.avg_fare_company/avg_trip_km as avg_price_per_km from (
SELECT company, avg(trip_km) as avg_trip_km, avg(fare) as avg_fare_company
FROM `ftds-hacktiv8-project.phase0_ftds_027_hck.taxi_fare`
group by company
) as x


'''
).to_dataframe()

df_1

'\nDari sini kita bisa melihat bahwa company Atomic Inc.\tmemiliki harga paling mahal yaitu dengan tarif 2.40 per km nya\nlalu untuk yang paling murah adalah company Rocket Cab Auto\tdengan taruk 1.67 per km nya\n'

**2. Pandas**

In [7]:
'''
pembuatan dataframe menggunakan pandas
'''
df_1 = client.query(
    '''

SELECT *
FROM `ftds-hacktiv8-project.phase0_ftds_027_hck.taxi_fare`


'''
).to_dataframe()

df_1 # menampilkan dataframe

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_km,fare,tips,payment_type,company,pickup_location,dropoff_location
0,AI-10273,A-318,2021-02-09 18:30:00+00:00,2021-02-09 18:30:00+00:00,0.482802,4.50,0.0,Cash,Atomic Inc.,POINT (-87.6251921424 41.8788655841),POINT (-87.6333080367 41.899602111)
1,AI-10159,A-318,2021-01-08 15:45:00+00:00,2021-01-08 16:00:00+00:00,1.770274,8.25,0.0,Cash,Atomic Inc.,POINT (-87.6635175498 41.874005383),POINT (-87.6251921424 41.8788655841)
2,AI-10889,A-318,2021-04-06 10:45:00+00:00,2021-04-06 10:45:00+00:00,3.540548,9.25,0.0,Cash,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6203346241 41.8571838585)
3,AI-10670,A-324,2021-03-18 15:30:00+00:00,2021-03-18 15:45:00+00:00,1.448406,5.75,0.0,Cash,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6333080367 41.899602111)
4,AI-10929,A-324,2021-04-08 19:15:00+00:00,2021-04-08 19:45:00+00:00,21.082354,34.75,0.0,Credit Card,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6488950721 41.7174930361)
...,...,...,...,...,...,...,...,...,...,...,...
9281,DP-784,D-51,2021-08-22 20:45:00+00:00,2021-08-22 21:15:00+00:00,28.968120,44.25,30.0,Credit Card,Deluc Porter,POINT (-87.9030396611 41.9790708201),POINT (-87.6188683546 41.8909220259)
9282,DP-927,P-116,2021-09-21 21:00:00+00:00,2021-09-21 21:30:00+00:00,29.450922,45.00,30.0,Credit Card,Deluc Porter,POINT (-87.9030396611 41.9790708201),POINT (-87.6209929134 41.8849871918)
9283,DP-174,D-113,2021-04-02 14:45:00+00:00,2021-04-02 16:15:00+00:00,99.296278,146.00,32.2,Credit Card,Deluc Porter,POINT (-87.913624596 41.9802643146),POINT (-87.913624596 41.9802643146)
9284,AI-11519,AI-555,2021-05-18 16:45:00+00:00,2021-05-18 17:45:00+00:00,20.921420,3.25,33.0,Credit Card,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.7696154528 41.7925923603)
9285,FI-3194,I-407,2022-06-19 20:45:00+00:00,2022-06-19 21:15:00+00:00,10.782578,21.00,100.0,Credit Card,Federway Int.,POINT (-87.6559981815 41.9442266014),POINT (-87.6763559892 41.9012069941)

In [8]:
df_1['period']= df_1['trip_start_timestamp'].dt.hour
df_1['period'] = df_1['period'].map(str)
df_1['period']

0       18
1       15
2       10
3       15
4       19
        ..
9281    20
9282    21
9283    14
9284    16
9285    20
Name: period, Length: 9286, dtype: object

In [13]:
import numpy as np

df_1['period'] = np.where(df_1['period'] >= 3 & df_1['period'] <= 10, 'Morning', df_1['period'])
df_1

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [9]:
df_1

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_km,fare,tips,payment_type,company,pickup_location,dropoff_location,period
0,AI-10273,A-318,2021-02-09 18:30:00+00:00,2021-02-09 18:30:00+00:00,0.482802,4.50,0.0,Cash,Atomic Inc.,POINT (-87.6251921424 41.8788655841),POINT (-87.6333080367 41.899602111),18
1,AI-10159,A-318,2021-01-08 15:45:00+00:00,2021-01-08 16:00:00+00:00,1.770274,8.25,0.0,Cash,Atomic Inc.,POINT (-87.6635175498 41.874005383),POINT (-87.6251921424 41.8788655841),15
2,AI-10889,A-318,2021-04-06 10:45:00+00:00,2021-04-06 10:45:00+00:00,3.540548,9.25,0.0,Cash,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6203346241 41.8571838585),10
3,AI-10670,A-324,2021-03-18 15:30:00+00:00,2021-03-18 15:45:00+00:00,1.448406,5.75,0.0,Cash,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6333080367 41.899602111),15
4,AI-10929,A-324,2021-04-08 19:15:00+00:00,2021-04-08 19:45:00+00:00,21.082354,34.75,0.0,Credit Card,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.6488950721 41.7174930361),19
...,...,...,...,...,...,...,...,...,...,...,...,...
9281,DP-784,D-51,2021-08-22 20:45:00+00:00,2021-08-22 21:15:00+00:00,28.968120,44.25,30.0,Credit Card,Deluc Porter,POINT (-87.9030396611 41.9790708201),POINT (-87.6188683546 41.8909220259),20
9282,DP-927,P-116,2021-09-21 21:00:00+00:00,2021-09-21 21:30:00+00:00,29.450922,45.00,30.0,Credit Card,Deluc Porter,POINT (-87.9030396611 41.9790708201),POINT (-87.6209929134 41.8849871918),21
9283,DP-174,D-113,2021-04-02 14:45:00+00:00,2021-04-02 16:15:00+00:00,99.296278,146.00,32.2,Credit Card,Deluc Porter,POINT (-87.913624596 41.9802643146),POINT (-87.913624596 41.9802643146),14
9284,AI-11519,AI-555,2021-05-18 16:45:00+00:00,2021-05-18 17:45:00+00:00,20.921420,3.25,33.0,Credit Card,Atomic Inc.,POINT (-87.6333080367 41.899602111),POINT (-87.7696154528 41.7925923603),16
9285,FI-3194,I-407,2022-06-19 20:45:00+00:00,2022-06-19 21:15:00+00:00,10.782578,21.00,100.0,Credit Card,Federway Int.,POINT (-87.6559981815 41.9442266014),POINT (-87.6763559892 41.9012069941),20

In [12]:
'''
Code ini untuk menampilkan data dari perusahaan Federway Int. pada tahun 2022.

penjelasan:
saya membuat dataframe baru yang bernama df_baru untuk menampung data yang akan dicari.
Data tersebut didapat dari pengambilan data pada df_1 dengan kolom company yang bernilai 'Federway Int.' dan harus memiliki rentan tanggal 1 january 2022 hingga 31 desember 2022 pada kolom trip_end_timestamp
nanti dataframe tersebut akan diolah lagi untuk mencari tahu total jarak perjalanan di bawah codingan ini.

analisa:
Dari data ini kita dapat menyimpulkan bahwa ada 1059 transaksi dari perusahaan Federway Int. pada tahun 2022
'''

df_baru = df_1[(df_1['company'] == 'Federway Int.') & ((df_1['trip_end_timestamp'] >= '2022-01-01') & (df_1['trip_end_timestamp'] <= '2022-12-31'))]
df_baru

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_km,fare,tips,payment_type,company,pickup_location,dropoff_location,period
1147,FI-3380,F-397,2022-07-21 20:00:00+00:00,2022-07-21 20:15:00+00:00,2.414010,8.25,0.00,Cash,Federway Int.,POINT (-87.6327464887 41.8809944707),POINT (-87.6129454143 41.8919715078),20
1148,FI-4033,F-397,2022-12-14 18:00:00+00:00,2022-12-14 18:00:00+00:00,1.126538,6.50,0.00,Cash,Federway Int.,POINT (-87.6262149064 41.8925077809),POINT (-87.6327464887 41.8809944707),18
1150,FI-3745,F-397,2022-10-12 17:45:00+00:00,2022-10-12 18:00:00+00:00,2.574944,8.00,0.00,Cash,Federway Int.,POINT (-87.6173580061 41.859349715),POINT (-87.6221729369 41.8706073724),17
1151,FI-3899,F-397,2022-11-15 16:45:00+00:00,2022-11-15 17:00:00+00:00,1.931208,7.50,0.00,Cash,Federway Int.,POINT (-87.6209929134 41.8849871918),POINT (-87.6378442095 41.8932163595),16
1153,FI-3201,F-397,2022-06-20 18:45:00+00:00,2022-06-20 19:00:00+00:00,2.092142,7.25,0.00,Cash,Federway Int.,POINT (-87.6241352979 41.8492467545),POINT (-87.6221729369 41.8706073724),18
...,...,...,...,...,...,...,...,...,...,...,...,...
9183,FI-3021,I-545,2022-05-25 17:45:00+00:00,2022-05-25 19:00:00+00:00,28.163450,48.75,14.75,Credit Card,Federway Int.,POINT (-87.6327464887 41.8809944707),POINT (-87.9030396611 41.9790708201),17
9198,FI-3150,I-537,2022-06-11 20:30:00+00:00,2022-06-11 20:45:00+00:00,4.023350,10.50,15.00,Credit Card,Federway Int.,POINT (-87.6219716519 41.8774061234),POINT (-87.6572331997 41.8852813201),20
9199,FI-3420,I-634,2022-07-28 17:45:00+00:00,2022-07-28 18:15:00+00:00,5.471756,14.50,15.00,Credit Card,Federway Int.,POINT (-87.6251921424 41.8788655841),POINT (-87.6494887289 41.9226862843),17
9228,FI-3675,F-422,2022-09-20 17:15:00+00:00,2022-09-20 18:15:00+00:00,31.221196,50.50,15.25,Credit Card,Federway Int.,POINT (-87.6219716519 41.8774061234),POINT (-87.9030396611 41.9790708201),17
9285,FI-3194,I-407,2022-06-19 20:45:00+00:00,2022-06-19 21:15:00+00:00,10.782578,21.00,100.00,Credit Card,Federway Int.,POINT (-87.6559981815 41.9442266014),POINT (-87.6763559892 41.9012069941),20

In [16]:
'''
Code ini untuk menampilkan total perjalanan yang dicapai perusahaan Federway Int. pada tahun 2022

penjelasan:
dari hasil dataframe yang sebelum ini yaitu df_baru. kita mengambil total trip_km nya menggunakan metode .sum()
caranya adalah setiap nilai yang ada di kolom trip_km pada df_baru akan di tambahkan semuanya dan dicantumkan hasil penjumlahannya di paling bawah

analisa:
dari 1060 transaksi yang dilakukan oleh company Federway Int. pada tahun 2022, Mereka telah menyelesaikan trip sejauh 4359.24 km.
'''

import pandas as pd

df_baru.loc['trip_km'] = pd.Series(df_baru['trip_km'].sum(), index=['trip_km'])
df_baru

<ipython-input-16-0ccd7cb857d8>:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_baru.loc['trip_km'] = pd.Series(df_baru['trip_km'].sum(), index=['trip_km'])
<ipython-input-16-0ccd7cb857d8>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_baru.loc['trip_km'] = pd.Series(df_baru['trip_km'].sum(), index=['trip_km'])

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_km,fare,tips,payment_type,company,pickup_location,dropoff_location,period
1147,FI-3380,F-397,2022-07-21 20:00:00+00:00,2022-07-21 20:15:00+00:00,2.414010,8.25,0.00,Cash,Federway Int.,POINT (-87.6327464887 41.8809944707),POINT (-87.6129454143 41.8919715078),20
1148,FI-4033,F-397,2022-12-14 18:00:00+00:00,2022-12-14 18:00:00+00:00,1.126538,6.50,0.00,Cash,Federway Int.,POINT (-87.6262149064 41.8925077809),POINT (-87.6327464887 41.8809944707),18
1150,FI-3745,F-397,2022-10-12 17:45:00+00:00,2022-10-12 18:00:00+00:00,2.574944,8.00,0.00,Cash,Federway Int.,POINT (-87.6173580061 41.859349715),POINT (-87.6221729369 41.8706073724),17
1151,FI-3899,F-397,2022-11-15 16:45:00+00:00,2022-11-15 17:00:00+00:00,1.931208,7.50,0.00,Cash,Federway Int.,POINT (-87.6209929134 41.8849871918),POINT (-87.6378442095 41.8932163595),16
1153,FI-3201,F-397,2022-06-20 18:45:00+00:00,2022-06-20 19:00:00+00:00,2.092142,7.25,0.00,Cash,Federway Int.,POINT (-87.6241352979 41.8492467545),POINT (-87.6221729369 41.8706073724),18
...,...,...,...,...,...,...,...,...,...,...,...,...
9198,FI-3150,I-537,2022-06-11 20:30:00+00:00,2022-06-11 20:45:00+00:00,4.023350,10.50,15.00,Credit Card,Federway Int.,POINT (-87.6219716519 41.8774061234),POINT (-87.6572331997 41.8852813201),20
9199,FI-3420,I-634,2022-07-28 17:45:00+00:00,2022-07-28 18:15:00+00:00,5.471756,14.50,15.00,Credit Card,Federway Int.,POINT (-87.6251921424 41.8788655841),POINT (-87.6494887289 41.9226862843),17
9228,FI-3675,F-422,2022-09-20 17:15:00+00:00,2022-09-20 18:15:00+00:00,31.221196,50.50,15.25,Credit Card,Federway Int.,POINT (-87.6219716519 41.8774061234),POINT (-87.9030396611 41.9790708201),17
9285,FI-3194,I-407,2022-06-19 20:45:00+00:00,2022-06-19 21:15:00+00:00,10.782578,21.00,100.00,Credit Card,Federway Int.,POINT (-87.6559981815 41.9442266014),POINT (-87.6763559892 41.9012069941),20
trip_km,NaN,NaN,NaT,NaT,4359.241350,NaN,NaN,NaN,NaN,NaN,NaN,NaN